### ISSUE TITLE
Should we semanticate already emphasised phrases?

### ISSUE THREAD

**Issue by drgrigg** [samlaws/jules-verne_an-antarctic-mystery#3]
@acabal may need to advise on this one. In Chapter 15 you've correctly semanticated a stand-alone reference to a ship's name. But I'm not sure what should be done where we have a ship name which is ALSO emphasised speech.

Alex, should: 

`<em>The Jane of Liverpool!</em>`

be:

`<i epub:type="se:name.vessel.ship">The Jane of Liverpool!</i>`

or even

`<em><i epub:type="se:name.vessel.ship">The Jane of Liverpool</i>!</em>`

**Comment by drgrigg** [comment]
Robin is suggesting that it be:

`<em epub:type="se:name.vessel.ship">The Jane of Liverpool!</em>`

**Comment by samlaws** [comment]
Will wait for confirmation here before doing anything, I like Robin's suggestion though. Note that there are two instances of this in the same couple of lines - I'm assuming changing one means changing the other?

**Comment by drgrigg** [comment]
Yes, change both.

**Comment by acabal** [comment]
Robin's suggestion would be correct in most cases except in this case the exclamation point isn't part of the ship's name. So in this case I would do it like so: `<em><span epub:type="se:name.vessel.ship">The Jane of Liverpool</span>!</em>`.

**Comment by samlaws** [comment]
So for the two instances I have made the following changes:

`<em>The Jane of Liverpool</em>!` -> `<em epub:type="se:name.vessel.ship">The Jane of Liverpool</em>!`

`<em>The Jane of Liverpool!</em>` -> `<em><span epub:type="se:name.vessel.ship">The Jane of Liverpool</span>!</em>`
