### ISSUE TITLE
Could replace book-title class with specific CSS selectors

### ISSUE THREAD

**Issue by drgrigg** [samlaws/jules-verne_an-antarctic-mystery#4]
You've created a class book-title which has three instances. Ideally we like to avoid classes which are only used once or twice. In this case, the instance in chapter 15  doesn't require small-caps (and in fact I don't think it _ought_ to be small-caps as the broken inscription is the rare case of genuine all-caps).

You could do this instead in local.css:

```
#chapter-5 blockquote,
#chapter-7 blockquote{
  text-align: center;
  font-variant: small-caps;
}

#chapter-5 blockquote p,
#chapter-7 blockquote p,
#chapter-15  blockquote p{
  text-indent: 0;
}

#chapter-15 blockquote{
  text-align: center;
}
```

And lose the class="book-title" references in the body text.

**Comment by samlaws** [comment]
Thanks David, I wasn't happy with the way I'd done it at all but lack(ed) the CSS skills to do it properly
