### ISSUE TITLE
There are a number of typos in the long description

### ISSUE THREAD

**Issue by drgrigg** [samlaws/jules-verne_an-antarctic-mystery#6]
I spotted these:

`Len Guys brother` (needs apostrophe before s)

`to lead a voyage to the Antarctic, the expedition` (should be a period not a comma, new sentence)

The start of the last paragraph is a bit of a mess  I think it ought to read something like:

`Despite the fact that Poe's work after its inspiration...` (note no apostrophe in its)

Last sentence should read:

`south to the Antarctic in search of any` (note missing word 'of')

**Comment by drgrigg** [comment]
Sorry, typo in my OWN post!!

`Despite the fact that Poe's work was published over fifty years after its inspiration...`

**Comment by samlaws** [comment]
Apologies for some shockers here David, must try writing the description outside of HTML next time and then porting over.
